image: python:3.9

stages:
  - deploy

before_script:
  - apt-get update -qq
  - pip install awscli

deploy_to_s3:
  stage: deploy
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
    - aws s3 cp path/to/local/file s3://your-bucket/path/to/destination/file
